/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.ProdukDAO;
import dao.ProduksiDAO;
import model.Produk;
import model.Produksi;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.print.*;
/**
 *
 * @author catur
 */
public class FormLaporan extends javax.swing.JFrame {
    
    private DefaultTableModel modelProduk;
    private DefaultTableModel modelProduksi;

    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
        initComponents();
        modelProduk = new DefaultTableModel();

        modelProduk.addColumn("Kode");
        modelProduk.addColumn("Nama");
        modelProduk.addColumn("Kategori");
        modelProduk.addColumn("Stok");
        modelProduk.addColumn("Keterangan");

        tblProduk.setModel(modelProduk);

        modelProduksi = new DefaultTableModel();

        modelProduksi.addColumn("ID");
        modelProduksi.addColumn("Kode Produk");
        modelProduksi.addColumn("Jumlah");
        modelProduksi.addColumn("Tanggal");
        modelProduksi.addColumn("Status");

        tblProduksi.setModel(modelProduksi);

        tampilProduk();
        tampilProduksi();
    }
    private void tampilProduk() {

    modelProduk.setRowCount(0);

    ProdukDAO dao =
            new ProdukDAO();

    List<Produk> list =
            dao.getAll();

    for(Produk p : list){

        modelProduk.addRow(new Object[]{

            p.getKodeProduk(),
            p.getNamaProduk(),
            p.getKategori(),
            p.getStok(),
            p.getKeterangan()

        });
    }
}
    private void tampilProduksi() {

    modelProduksi.setRowCount(0);

    ProduksiDAO dao =
            new ProduksiDAO();

    List<Produksi> list =
            dao.getAll();

    for(Produksi p : list){

        modelProduksi.addRow(new Object[]{

            p.getIdProduksi(),
            p.getKodeProduk(),
            p.getJumlah(),
            p.getTanggalProduksi(),
            p.getStatus()

        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("LAPORAN PRODUK DAN PRODUKSI");

        btnCetak.setBackground(new java.awt.Color(51, 255, 204));
        btnCetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(51, 255, 204));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("DATA PRODUK");

        tblProduk.setBackground(new java.awt.Color(51, 255, 204));
        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProduk);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DATA PRODUKSI");

        jScrollPane2.setBackground(new java.awt.Color(0, 204, 153));

        tblProduksi.setBackground(new java.awt.Color(51, 255, 204));
        tblProduksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProduksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(btnCetak)
                                .addGap(18, 18, 18)
                                .addComponent(btnKembali))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(305, 305, 305)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 222, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(241, 241, 241))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(282, 282, 282))))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetak)
                    .addComponent(btnKembali))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuUtama().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        btnCetak.setVisible(false);
        btnKembali.setVisible(false);

        PrinterJob job = PrinterJob.getPrinterJob();

        job.setJobName("Laporan Produk dan Produksi");

        job.setPrintable(new Printable() {

            @Override
            public int print(Graphics graphics,
                             PageFormat pageFormat,
                             int pageIndex)
                    throws PrinterException {

                if (pageIndex > 0) {
                    return NO_SUCH_PAGE;
                }

                Graphics2D g2 =
                        (Graphics2D) graphics;

                double scale = 0.7;

                double panelWidth =
                        getContentPane().getWidth() * scale;

                double x =
                        (pageFormat.getImageableWidth()
                        - panelWidth) / 2;

                g2.translate(
                        pageFormat.getImageableX() + x,
                        pageFormat.getImageableY());

                g2.scale(scale, scale);

                getContentPane().paint(g2);

                return PAGE_EXISTS;
            }
        });

        boolean ok = job.printDialog();

        if (ok) {

            try {

                job.print();

            } catch (PrinterException e) {

                JOptionPane.showMessageDialog(
                        this,
                        "Gagal Cetak : "
                        + e.getMessage());

            }
        }

        btnCetak.setVisible(true);
        btnKembali.setVisible(true);
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProduk;
    private javax.swing.JTable tblProduksi;
    // End of variables declaration//GEN-END:variables
}
